{{- if ((.Values.studioDatachainWorker).serviceAccount).create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "studio-datachain-worker.serviceAccountName" . }}-nodes
  labels:
    {{- include "studio-datachain-worker.labels" . | nindent 4 }}
  {{- with .Values.studioDatachainWorker.serviceAccount.annotations }}
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-delete-policy: hook-failed, before-hook-creation
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "studio-datachain-worker.serviceAccountName" . }}-nodes
subjects:
  - kind: ServiceAccount
    name: {{ include "studio-datachain-worker.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
